// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "3cc4d65e-7dd4-401b-9411-edbf7c43342f";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onLuzChange();
void onHumedadChange();

CloudLight luz;
CloudTemperatureSensor temperatura;
CloudRelativeHumidity humedad;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(luz, READWRITE, ON_CHANGE, onLuzChange);
  ArduinoCloud.addProperty(temperatura, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(humedad, READWRITE, ON_CHANGE, onHumedadChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
